apiVersion: v1
kind: Namespace
metadata:
  name: jungle
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: LimitRange
metadata:
  name: jungle
  namespace: jungle
spec:
  limits:
  - max:
      cpu: "4"
      memory: 6Gi
    min:
      cpu: 10m
      memory: 5Mi
    type: Pod
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 50m
      memory: 100Mi
    max:
      cpu: "3"
      memory: 5Gi
    min:
      cpu: 10m
      memory: 3Mi
    type: Container