# A simple example of ClusterConfig object with two nodegroups:
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-pub-testing-1
  region: eu-west-1

nodeGroups:
  - name: nodegroup-pub-1
    instanceType: t3.medium
    desiredCapacity: 3
    ssh:
      allow: true
    subnets:
      - subnet-0a1c1b787505b7a77
      - subnet-095bbdeeb380fb372
      - subnet-07154af320a58c63b
