apiVersion: apps/v1
kind: Deployment
metadata:
  name: tank-deployment
  labels:
    app: tank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tank
  template:
    metadata:
      labels:
        app: tank
    spec:
      containers:
      - name: tank
        image: 612239922950.dkr.ecr.eu-west-1.amazonaws.com/tanks:0.0.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tank-service
spec:
  selector:
    app: tank
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer