apiVersion: v1
kind: Namespace
metadata:
  name: games
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: LimitRange
metadata:
  name: games
  namespace: games
spec:
  limits:
  - max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 10m
      memory: 5Mi
    type: Pod
  - default:
      cpu: 500m
      memory: 1Gi
    defaultRequest:
      cpu: 50m
      memory: 100Mi
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 10m
      memory: 3Mi
    type: Container